project:
  type: book
  execute-dir: project

book:
  title: "NanoLogix report"
  date: today
  sidebar:
    search: false
    title: "Contents"
    style: docked
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
    - part: "Quality control"
      chapters:
        - sequencing_qc.qmd
        - library_qc.qmd
    - part: panning.qmd

bibliography: template/references.bib
csl: template/vancouver_superscript.csl
format:
  html:
    grid:
      body-width: 1400px
      margin-width: 20px
      sidebar-width: 300px
    theme: template/litera_edited.scss
    code-fold: true
    fig-width: 10
    fig-height: 5
    fig-dpi: 200
    code-summary: "Show code"
    code-block-bg: true
    code-tools: true
    toc: false
    monobackgroundcolor: "#fbf0ed"
    highlight-style: atom-one
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,700;1,700&family=Poppins:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">